import type { Order, Product, WarehouseException } from "./types"

const MIN = 60 * 1000
const HOUR = 60 * MIN

export const ZONES = ["A", "B", "C", "D"] as const

export function seedProducts(): Product[] {
  return [
    {
      id: "p1",
      sku: "SKU-1001",
      name: "Anker 65W USB-C Charger",
      category: "Electronics",
      zone: "A",
      bin: "A-04-12",
      onHand: 7,
      allocated: 0,
      reorderPoint: 25,
      reorderQty: 120,
      incoming: 0,
      unitCost: 14.5,
      unitPrice: 39.99,
    },
    {
      id: "p2",
      sku: "SKU-1002",
      name: "Logitech MX Master 3S",
      category: "Electronics",
      zone: "A",
      bin: "A-02-05",
      onHand: 142,
      allocated: 18,
      reorderPoint: 40,
      reorderQty: 100,
      incoming: 0,
      unitCost: 61,
      unitPrice: 99.99,
    },
    {
      id: "p3",
      sku: "SKU-1003",
      name: "Sony WH-1000XM5 Headphones",
      category: "Electronics",
      zone: "A",
      bin: "A-06-01",
      onHand: 12,
      allocated: 4,
      reorderPoint: 20,
      reorderQty: 60,
      incoming: 40,
      unitCost: 210,
      unitPrice: 349.99,
    },
    {
      id: "p4",
      sku: "SKU-2001",
      name: "Hydro Flask 32oz Bottle",
      category: "Outdoors",
      zone: "B",
      bin: "B-01-09",
      onHand: 320,
      allocated: 60,
      reorderPoint: 80,
      reorderQty: 200,
      incoming: 0,
      unitCost: 12,
      unitPrice: 44.95,
    },
    {
      id: "p5",
      sku: "SKU-2002",
      name: "Osprey Talon 22 Backpack",
      category: "Outdoors",
      zone: "B",
      bin: "B-03-14",
      onHand: 3,
      allocated: 0,
      reorderPoint: 15,
      reorderQty: 50,
      incoming: 0,
      unitCost: 68,
      unitPrice: 149.95,
    },
    {
      id: "p6",
      sku: "SKU-2003",
      name: "Coleman 2-Person Tent",
      category: "Outdoors",
      zone: "B",
      bin: "B-05-02",
      onHand: 46,
      allocated: 8,
      reorderPoint: 20,
      reorderQty: 40,
      incoming: 0,
      unitCost: 55,
      unitPrice: 129.99,
    },
    {
      id: "p7",
      sku: "SKU-3001",
      name: "Nespresso Vertuo Pods (40ct)",
      category: "Home",
      zone: "C",
      bin: "C-02-07",
      onHand: 210,
      allocated: 35,
      reorderPoint: 100,
      reorderQty: 300,
      incoming: 0,
      unitCost: 18,
      unitPrice: 34.99,
    },
    {
      id: "p8",
      sku: "SKU-3002",
      name: "Dyson V8 Filter Kit",
      category: "Home",
      zone: "C",
      bin: "C-04-11",
      onHand: 0,
      allocated: 0,
      reorderPoint: 30,
      reorderQty: 90,
      incoming: 90,
      unitCost: 22,
      unitPrice: 49.99,
    },
    {
      id: "p9",
      sku: "SKU-3003",
      name: "Lodge Cast Iron Skillet 12in",
      category: "Home",
      zone: "C",
      bin: "C-01-03",
      onHand: 88,
      allocated: 12,
      reorderPoint: 30,
      reorderQty: 60,
      incoming: 0,
      unitCost: 19,
      unitPrice: 39.99,
    },
    {
      id: "p10",
      sku: "SKU-4001",
      name: "Theragun Mini Massager",
      category: "Wellness",
      zone: "D",
      bin: "D-03-08",
      onHand: 19,
      allocated: 6,
      reorderPoint: 25,
      reorderQty: 50,
      incoming: 0,
      unitCost: 89,
      unitPrice: 199.0,
    },
    {
      id: "p11",
      sku: "SKU-4002",
      name: "Manduka PRO Yoga Mat",
      category: "Wellness",
      zone: "D",
      bin: "D-01-15",
      onHand: 130,
      allocated: 20,
      reorderPoint: 40,
      reorderQty: 80,
      incoming: 0,
      unitCost: 42,
      unitPrice: 120.0,
    },
    {
      id: "p12",
      sku: "SKU-4003",
      name: "Whoop 4.0 Band",
      category: "Wellness",
      zone: "D",
      bin: "D-05-06",
      onHand: 9,
      allocated: 2,
      reorderPoint: 15,
      reorderQty: 45,
      incoming: 0,
      unitCost: 55,
      unitPrice: 0,
    },
  ]
}

export function seedOrders(now: number): Order[] {
  const line = (sku: string, name: string, qty: number) => ({
    sku,
    name,
    qty,
    allocated: 0,
    picked: 0,
  })

  return [
    // The classic scenario: urgent order needs 10 of a SKU that only has 7 on hand
    {
      id: "o1",
      code: "ORD-4821",
      customer: "Vertex Retail Group",
      customerTier: "platinum",
      priority: "urgent",
      createdAt: now - 22 * MIN,
      dueBy: now + 90 * MIN,
      stage: "created",
      status: "active",
      value: 0,
      lines: [line("SKU-1001", "Anker 65W USB-C Charger", 10)],
    },
    // Competing lower-priority order for the same scarce SKU
    {
      id: "o2",
      code: "ORD-4822",
      customer: "Corner Electronics",
      customerTier: "standard",
      priority: "standard",
      createdAt: now - 8 * MIN,
      dueBy: now + 8 * HOUR,
      stage: "created",
      status: "active",
      value: 0,
      lines: [line("SKU-1001", "Anker 65W USB-C Charger", 5)],
    },
    {
      id: "o3",
      code: "ORD-4810",
      customer: "Summit Outfitters",
      customerTier: "gold",
      priority: "high",
      createdAt: now - 55 * MIN,
      dueBy: now + 40 * MIN,
      stage: "allocated",
      status: "active",
      value: 0,
      lines: [
        line("SKU-2001", "Hydro Flask 32oz Bottle", 6),
        line("SKU-2003", "Coleman 2-Person Tent", 2),
      ],
    },
    {
      id: "o4",
      code: "ORD-4807",
      customer: "Bloom Wellness Studio",
      customerTier: "gold",
      priority: "high",
      createdAt: now - 70 * MIN,
      dueBy: now + 25 * MIN,
      stage: "picking",
      status: "active",
      value: 0,
      lines: [
        line("SKU-4002", "Manduka PRO Yoga Mat", 8),
        line("SKU-4001", "Theragun Mini Massager", 3),
      ],
    },
    {
      id: "o5",
      code: "ORD-4795",
      customer: "Northwind Home",
      customerTier: "standard",
      priority: "standard",
      createdAt: now - 2 * HOUR,
      dueBy: now + 6 * HOUR,
      stage: "packing",
      status: "active",
      value: 0,
      lines: [
        line("SKU-3001", "Nespresso Vertuo Pods (40ct)", 12),
        line("SKU-3003", "Lodge Cast Iron Skillet 12in", 4),
      ],
    },
    {
      id: "o6",
      code: "ORD-4788",
      customer: "Peak Performance Co.",
      customerTier: "platinum",
      priority: "urgent",
      createdAt: now - 3 * HOUR,
      dueBy: now + 15 * MIN,
      stage: "qc",
      status: "active",
      value: 0,
      lines: [line("SKU-1002", "Logitech MX Master 3S", 5)],
    },
    {
      id: "o7",
      code: "ORD-4770",
      customer: "Cascade Gear",
      customerTier: "gold",
      priority: "high",
      createdAt: now - 4 * HOUR,
      dueBy: now + 3 * HOUR,
      stage: "dispatch",
      status: "active",
      value: 0,
      lines: [line("SKU-2001", "Hydro Flask 32oz Bottle", 20)],
    },
    // Order that will be short — needs a product that's out of stock
    {
      id: "o8",
      code: "ORD-4825",
      customer: "Metro Appliances",
      customerTier: "gold",
      priority: "high",
      createdAt: now - 5 * MIN,
      dueBy: now + 2 * HOUR,
      stage: "created",
      status: "active",
      value: 0,
      lines: [line("SKU-3002", "Dyson V8 Filter Kit", 6)],
    },
    {
      id: "o9",
      code: "ORD-4826",
      customer: "Trailhead Supply",
      customerTier: "standard",
      priority: "standard",
      createdAt: now - 3 * MIN,
      dueBy: now + 10 * HOUR,
      stage: "created",
      status: "active",
      value: 0,
      lines: [line("SKU-2002", "Osprey Talon 22 Backpack", 4)],
    },
  ]
}

export function seedExceptions(now: number): WarehouseException[] {
  return [
    {
      id: "e1",
      type: "damaged",
      orderId: "o4",
      orderCode: "ORD-4807",
      sku: "SKU-4001",
      productName: "Theragun Mini Massager",
      qty: 1,
      zone: "D",
      detectedAt: now - 6 * MIN,
      status: "open",
      note: "Picker flagged crushed retail box at bin D-03-08.",
    },
  ]
}
